import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CarouselIstruttoriService {

  constructor() { }

  istruttori = [

    {id: 1,nome: 'Angelo Todaro' , descrizione: `Con un granitico bagaglio culturale nel settore del Body Building, Angelo Todaro rappresenta a pieno la filosofia Stoica di Elite Academy promuovendo il Sarcoplasma Stimulating Training. Classe 1976, Angelo proviene da un background di lotta Greco-Romana valsogli diversi titoli nazionali, approcciando la disciplina del Body Building in una fase più matura della sua formazione. Un forte carattere, una grande preparazione ed una tenace ambizione rendono Angelo Todaro non solo un eccellente formatore sportivo, ma lo inquadrano a pieno titolo nel ruolo di Mental Coach.<br><br>Se vuoi dare una smossa alle tue cattive abitudini e conferirti più disciplina, Angelo Todaro è il docente di cui hai bisogno.` , img : '../assets/media/angelo.jpg' , disciplina: 'Tecnico di Bodybuilding e Fitness'},

    {id: 2, nome: 'Anna Favata' , descrizione: `Giovane, Dinamica, Energica e Carismatica. Anna rappresenta perfettamente ciò che la costanza e la tenacia possono generare. Classe 1988, Anna ha cominciato la sua carriera sportiva all’età di 12 anni, sbarcando ad Elite Academy come allieva in un primo momento, distinguendosi da subito per la sua tenacia, costanza e passione per il Functional Training. Oggi Anna spicca come una delle stelle nascenti del nostro Team, formando atleti di tutte le età. Con un focus particolare sull’Endurance, Anna propone percorsi formativi d’allenamento che ti porteranno a spingere il pedale del gas fino in fondo.<br><br> <h6>Se cerchi un allenamento che ti svuoti la mente e ti riempia il cuore, Anna Favata è la docente per te.</h6>` , img : '../assets/media/anna.jpg' , disciplina: 'Functional Training'},

    {id: 3, nome: 'Antonino Catalano' , descrizione: `Al suono di ritmi calienti e serrati, la zumba con Antonino Catalano diventa energia pura.Prorompente, esplosivo e sempre attento alle esigenze di ogni studente, Antonino fa tremare i vetri di Elite Academy insieme ai suoi allievi. Con una lunga carriera nel mondo del Total Body, Antonino rappresenta uno degli elementi piu esplosivi del nostro Staff. La sua didattica saprà lasciarti senza fiato, con una scarica di adrenalina da far tremare le gambe.<br><br> Vuoi tenerti in forma dando sfogo alla tua energia con una classe sempre sorridente ed affiatata? Antonino Catalano è il docente per te.` , img : '../assets/media/catalano.jpg' , disciplina: 'Functional Training & Zumba'},

    {id: 4, nome: 'Antonio Lo Nardo' , descrizione: `Respirazione, ritmo e conoscenza di sé. Nessun vero atleta può dirsi tale senza dominare questi campi ed Antonio Lo Nardo lo sa. Membro del nostro Staff dal 2017, Antonio ha saputo incarnare la filosofia di disciplina e miglioramento che Elite Academy promuove. Con un background che varia dallo yoga alla danza, il Pilates di Antonio è un’esperienza olistica profonda per conoscere e migliorare sé stessi.  Creativo, disciplinato e riflessivo, Antonio ti regalerà un’esperienza di Wellness senza precedenti trasformando il tuo percorso di crescita in un’esperienza meravigliosa.<br><br> Se senti che il tuo corpo sia il tuo tempio e che prenderti cura del tuo tempio sia la tua missione, Antonio Lo Nardo è il docente che stai cercando.` , img : '../assets/media/lo nardo.jpg' , disciplina: 'Pilates'},

    {id: 5, nome: 'Francesca Mineo' , descrizione: `Eccellenza; Nessun termine potrebbe descrivere meglio la qualità che Francesca Mineo propone ai nostri studenti. Provenendo dai più alti ambienti accademici della danza classica, Francesca vanta nel suo background importanti successi con nomi di spicco della Televisione Italiana ed internazionale. Francesca ha fatto dell’insegnamento della Disciplina Artistica Accademica la sua vita, conseguendo titoli di studio in Scienze Motorie e Pedagogiche. Francesca è senza alcun dubbio uno dei fiori all’occhiello di Elite Academy, proponendo e promuovendo i valori accademici della disciplina e della costanza in cui noi da sempre crediamo.<br><br> Se la danza è la tua passione o la tua professione, Francesca Mineo è la docente che stai cercando.` , img : '../assets/media/mineo.jpg' , disciplina: 'Danza Moderna'},
    
    {id: 6, nome: 'Salvatore Consales' , descrizione: `Per essere un atleta serve avere anche il mindset giusto, e questo il nostro Presidente lo sa bene. Salvatore Consales, classe 1992, vanta nel suo curriculum importanti titoli a livello nazionale ed internazionale. Cominciando la carriera sportiva nel calcio, passando al Powerlifting e il Body Building, Salvatore è l’incarnazione dei valori di cui Elite Academy è pioniera. Con un focus particolare sul coaching per atleti agonisti, Salvatore ispira tutti noi ogni giorno alla resilienza ed al coraggio per affrontare nuove sfide. <br><br>Se hai deciso davvero di cambiare il tuo stile di vita e diventare la migliore versione di te stesso, Salvatore Consales è il docente che cerchi.` , img : '../assets/media/salvo.jpg' , disciplina: 'Tecnico di Bodybuilding & Powerlifting'},

    

    {id: 7, nome: 'Ilenia Leto' , descrizione: `Disciplina, autocontrollo e dedizione. Ilenia Leto, cintura nera secondo Dan, incarna profondamente la filosofia marziale che Elite Academy promuove. Coinvolgente e paziente, Ilenia cura la formazione dei nostri allievi sin dalla più giovane età, sapendo canalizzare l’energia dei suoi studenti verso il rispetto, la promozione della non violenza e dell’autodifesa. Il suo carattere controllato e disciplinato sono di forte ispirazione per tutti noi, e quando mescolati alla sua energia esplosiva generano un mix che non ha eguali.<br><br> Se stai cercando un full immersion nella disciplina delle arti marziali e sei pronto ad affrontare un percorso che ti cambierà la vita, Ilenia Leto è la docente che cerchi.` , img : '../assets/media/leto.jpg' , disciplina: 'Ju Jitsu'},

    // {id: 8, nome: 'Manuela Gagliardo' , descrizione: `La cura del corpo passa anche dalla cura della mente. Manuela Gagliardo, energica ed esplosiva, ha combinato questi due aspetti in una formula d’allenamento che ti lascerà senza fiato. Pronti a sfogare lo stress della settimana? Allora allacciate le cinture, perché’ Manuela saprà farvi muovere in 60 minuti più di quanto non lo abbiate mai fatto nella vostra vita. Con un sorriso sulla faccia ed al ritmo incalzante del suo pump, Manuela ha la formula magica per il corpo che sogni e quella scarica d’adrenalina trovi solo ad Elite Academy.<br><br> Se sei in cerca di una sfida con te stesso e vuoi alzare l’astina del tuo limite sempre più in alto, Manuela Gagliardo è la docente di cui hai bisogno.` , img : '../assets/media/test2.jpg' , disciplina: 'Functional Training'},

    {id: 9, nome: 'Martina Di Bella' , descrizione: `Senti le pareti tremare? Sono gli allievi di Martina Di Bella che si stanno solo riscaldando. Guidata da un variegato background nel mondo del fitness e della danza, Martina sa dare all Hip Hop New Style un’impronta unica ed esplosiva. Docente decisa e testarda, ha approcciato la danza all’età di 5 anni senza più fermarsi. Quando Martina accende il mixer ed i suoi studenti allacciano le scarpe, il parquet dell’Elite Academy sa che sarà una dura giornata. Quando l’occasione di trovarti sotto i riflettori si presenterà, non lasciarti trovare impreparato. Sky’s the limit babe. <br><br>Senti anche tu quel ritmo dentro che non sai proprio controllare? Martina Di Bella è la docente di cui hai bisogno.` , img : '../assets/media/di bella.jpg' , disciplina: 'Hip Hop'},

    {id: 10, nome: 'Piero Fontana' , descrizione: `Desiderio, Dedizione, Determinazione, Disciplina. La filosofia delle quattro D che Piero Fontana promuove qui ad Elite Academy è la formula magica per il tuo successo. Forte del suo glorioso passato nel Karate, Piero Fontana vanta una formazione a cinque stelle che saprà far decollare il tuo allenamento olistico verso un\'altra dimensione. Piero combina la sua innata attitudine all’insegnamento a grandi abilita di comunicatore, dimostrandosi imbattibile nel motivarti a migliorare ogni giorno. <br><br>Se sposi la filosofia del Mens Sana in Corpore Sano, Piero Fontana è il docente che cerchi.`  , img : '../assets/media/fontana.jpg' , disciplina: 'Olistico'},

    {id: 11, nome: 'Giuseppe Ferrara' , descrizione: `Con titoli regionali e nazionali, Giuseppe Ferrara incarna perfettamente il ruolo di docente vecchio stampo qui Elite Academy. Cominciando la sua carriera nel Judo durante la leva militare, Giuseppe si inquadra come Docente di Metodo Globale di Autodifesa Fijlkam. Approcciando la disciplina nel 1966, Giuseppe è un vero conservatore dei valori di rispetto, disciplina e lealtà che caratterizzano il Judo e di cui Elite Academy si fa portavoce. Ciò nonostante, Giuseppe sa sempre stare al passo con una disciplina ch’è in continua evoluzione, sapendola combinare con una didattica adatta a tutte le fasce d’età.<br><br> Se vuoi sviluppare il coraggio necessario ad affrontare la vita, facendo al contempo tuoi i più alti principi morali, Giuseppe Ferrara è il docente di cui hai bisogno.` , img : '../assets/media/ferrara.jpg' , disciplina: 'Judo'},

    {id: 12, nome: 'Salvo Virzì' , descrizione: `Combattimento, Forma e Tecnica. Questi i tre pilastri del Karate sui quali la didattica del Maestro Salvo Virzì si basa. Avendo formato molteplici atleti, fino alla nazionale italiana, Salvo sa mescolare una pluriennale conoscenza della tradizione del karate con le più innovative tecniche del fitness.  Avendo dedicato la sua vita a questa disciplina e vivendo a pieno lo stile di vita, Salvo sa essere un baluardo di ispirazione per i nostri studenti qui ad Elite Academy. <br><br>Se sei pronto a cominciare un percorso di disciplina e formazione fisico-mentale che ti formerà per tutta la vita, Salvo Virzi è il docente che cerchi.`, img : '../assets/media/virzì.jpg' , disciplina: 'Karate'},

    {id: 13, nome: 'Simona Marino' , descrizione: `Quando il ritmo ti lascia senza fiato non c’è dubbio, sei in una classe di Simona Marino. Forte, ribelle e creativa, Simona porta ad Elite Academy il colore di cui non sapremmo fare a meno. Nata con la musica nel sangue, Simona sa come spezzare la tua routine e trascinarti in una spirale travolgente di ritmo e divertimento senza eguali. Carica di energia, Simona sa sempre come condire i suoi allenamenti con quell’euforia che la contraddistingue. Allora musica al massimo, asciugamano a portata di mano e un respiro profondo perché’ Simona è già sul palco. <br><br>Se la musica è parte fondamentale del tuo allenamento vai sul sicuro, Simona Marino è la docente che cerchi.`, img : '../assets/media/marino.jpg' , disciplina: 'Balli di Gruppo & Zumba'},

    {id: 14, nome: 'Davide Randazzo' , descrizione: `Per ottenere i risultati che desideri avrai bisogno di costanza, di una guida e di un motivatore. Qui ad Elite Academy lo sappiamo, ed è per questo che siamo lieti di aver inserito nel nostro Staff un docente così versatile e completo come Davide. Con la sua preparazione ed il suo carisma, Davide sarà essere la guida verso quel miglioramento fisico che hai a lungo desiderato. La sua disciplina e la sua serietà fanno di Davide il docente ideale per la tua routine d’allenamento. La sua lunga esperienza nel mondo del fitness e del Body Building rendono Davide uno dei nostri uomini di punta. <br><br>Se un allenamento mirato e ben curato nei minimi dettagli è ciò che cerchi, Davide Randazzo è il docente che cerchi.`, img : '../assets/media/randazzo.jpg' , disciplina: 'Tecnico di Bodybuilding e Fitness'},
  ]

}


